### ISSUE TITLE
unexpected keyword argument "auth"

### ISSUE THREAD

**Issue by davletovb** [lucaschapin/dash-google-auth#18]
I'm getting an error: Dash() got an unexpected keyword argument 'auth'

**Comment by sabpap** [comment]
I'm getting the same error. How did you solve this?

**Comment by redm123** [comment]
Looks like it can simply be left out... Then maybe the sample should be adjusted accordingly.
(Note: I didn't really try with Google, but used this to implement a custom oauth flow)
