### ISSUE TITLE
Error: invalid_client

### ISSUE THREAD

**Issue by delaleva** [lucaschapin/dash-google-auth#2]
I did all of the steps from the README.md file and replaced the variables for client ID and client secret with real values like this:
```
app.server.config["GOOGLE_OAUTH_CLIENT_ID"] = os.environ.get("client-id-here")
        app.server.config["GOOGLE_OAUTH_CLIENT_SECRET"] = os.environ.get("client-secret-here")
```

However, when I ran python app.py and opened "localhost:5000" in my browser I got the following error:

```
401. That’s an error.

Error: invalid_client

The OAuth client was not found.

Request Details
response_type=code
client_id=None
redirect_uri=http://localhost:5000/login/google/authorized
scope=profile email
state=1kPQ9gCwR3EkGbXV5LdnPLu1TgQEpn
access_type=offline
approval_prompt=force
That’s all we know.
```
I put the following into the “Authorized redirect URIs” field: `http://localhost:5000/login/google/authorized`

When I tried out the example from the Flask Dance Guide link you have provided, I got redirected to Google login. After I logged in I tried running app.py again and this time I could access the page because I was already authenticated.

Is there a way to fix this problem? I would like to your google example in my application, thank you.

**Comment by lchapo** [comment]
@delaleva you can see from the error message that the client_id isn't being set properly. os.environ.get() attempts to locate an environment variable in your bash profile, so the value here should be a key rather than the client id itself.

If you want to set the config values directly (fine for testing but never do this in production), your code would need to look like this:
```
app.server.config["GOOGLE_OAUTH_CLIENT_ID"] = "client-id-here"
app.server.config["GOOGLE_OAUTH_CLIENT_SECRET"] = "client-secret-here"
```

**Comment by delaleva** [comment]
What a silly mistake, thanks a lot.
