### ISSUE TITLE
Redirected automatically to localhost when moving to production environment

### ISSUE THREAD

**Issue by 0xAtomist** [lucaschapin/dash-google-auth#8]
Upon moving this to my production server I'm running into the issue that I am automatically redirected to http://localhost/login/google/authorized which is not on my authorised URI list on google, rather than redirecting to https://mydomain.com/login/google/authorized.

I have looked through the code as well as the flask_dance/make_google_blueprint docs but can't seem to find where this default routing to localhost would happen.

Any advice would be greatly appreciated.

**Comment by lchapo** [comment]
There's nothing in this example repo that specifically redirects to localhost, so I would imagine this has to do with how you've configured your deployment process.

**Comment by 0xAtomist** [comment]
Is there anywhere in the repo where I can specify a redirect URI of my choosing?

**Comment by lchapo** [comment]
You could redirect to an external URI after the authentication process. For example, on [Line 60 of google_oauth.py](https://github.com/lucaschapin/dash-google-auth/blob/master/app/google_oauth.py#L60) you could replace:
`return original_index(*args, **kwargs)`
with
`return redirect("https://www.google.com")`

**Comment by 0xAtomist** [comment]
Thanks for the response. Just tried that little fix but to no avail. Guess I will need to dig deeper to find the source of the issue in my configuration. For reference this is the URL I'm being redirected when I go to https://mydomain.com/login/google which gives a redirect_uri_mismatch error:

https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=248251904757-ahcjadlvnca0h592jgjgo7go2caeu297.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%2Flogin%2Fgoogle%2Fauthorized&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&state=IM9mUnO9Nf5BBYYx6gVoqD28EnYtbL&approval_prompt=force&access_type=offline

If I go directly to https://mydomain.com I get redirected to http://localhost/login/google as suggested in the URL above.

**Comment by lchapo** [comment]
Gotcha. I think this is a general flask issue rather than something specific to flask_dance, so I'd try googling search terms like "flask redirects to localhost" -- there's some stuff that looks like it might be helpful for your issue.

**Comment by 0xAtomist** [comment]
@lucaschapin, thanks for the direction you were certainly right, the issue was in my nginx configuration.
